version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: users_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]