version: "3.9"

services:
  user:
    container_name: user_api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /app/src
    depends_on:
      - postgres
    network_mode: bridge
    volumes:
      - ./:/app/src
    ports:
      - ${PORT_LOCAL}:${PORT}
    environment:
      - APP_MODE=${APP_MODE}
      - HOST=${HOST}
      - PORT=${PORT}
      - PORT_LOCAL=${PORT_LOCAL}
      - SERVER_MODE=${SERVER_MODE}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT_NUMBER}

  postgres:
    image: postgres:latest
    container_name: users_pg
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: bitnami/redis:latest
    network_mode: bridge
    volumes:
      - /redis/persistence/data
    environment:
      - REDIS_DISABLE_COMMANDS=${REDIS_DISABLE_COMMANDS}
      - ALLOW_EMPTY_PASSWORD=${REDIS_ALLOW_EMPTY_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT_NUMBER}
    ports:
      - '${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb