version: "3.5"
services:
  user:
    container_name: user_api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /app/src
    volumes:
      - ./:/app/src
    ports:
      - ${USER_PORT_LOCAL}:${USER_PORT}
    environment:
      - APP_MODE=${APP_MODE}
      - HOST=${USER_HOST}
      - PORT=${USER_PORT}
      - PORT_LOCAL=${USER_PORT_LOCAL}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT_NUMBER}
    command: ["go", "run", "main.go"]

  postgres:
    image: postgres:latest
    container_name: users_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: bitnami/redis:latest
    volumes:
      - /redis/persistence/data
    environment:
      - REDIS_DISABLE_COMMANDS=${REDIS_DISABLE_COMMANDS}
      - ALLOW_EMPTY_PASSWORD=${REDIS_ALLOW_EMPTY_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT_NUMBER}
    ports:
      - '${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb